# Generated by Django 3.1.2 on 2021-01-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(default='', max_length=50, verbose_name='Last name')),
                ('email', models.CharField(default='', max_length=50, verbose_name='Phone number')),
                ('company', models.CharField(default='', max_length=50, verbose_name='High school')),
            ],
        ),
    ]
