# Generated by Django 3.1.2 on 2021-01-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='upload/no_img.png', null=True, upload_to='upload/')),
                ('first_name', models.CharField(default='', max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(default='', max_length=50, verbose_name='Last name')),
                ('address', models.TextField(default='', max_length=255, verbose_name='Address')),
                ('about_me', models.TextField(default='', max_length=300, verbose_name='About me')),
                ('interest', models.TextField(default='', max_length=300, verbose_name='Interest')),
                ('phone_number', models.CharField(default='', max_length=10, verbose_name='Phone number')),
                ('high_school', models.CharField(default='', max_length=50, verbose_name='High school')),
                ('high_school_gpa', models.FloatField(default=0.0, max_length=4, verbose_name='High school gpa')),
                ('university', models.CharField(default='', max_length=30, verbose_name='University')),
                ('department', models.CharField(default='', max_length=30, verbose_name='Department')),
                ('faculty', models.CharField(default='', max_length=30, verbose_name='Faculty')),
                ('university_gpa', models.FloatField(default=0.0, max_length=4, verbose_name='University gpa')),
            ],
        ),
    ]
